### ISSUE TITLE
`torch._foreach...` implementation

### ISSUE THREAD

**Issue by bonlime** [sail-sg/Adan#1]
Hi, very interesting work! 
The only problem i see is that your optimizer is slower that sgd/adamw which may discourage some people from using it. Do you plan adding an implementation using `torch._foreach...` functions? Examples [could be seen in torch.optim](https://github.com/pytorch/pytorch/blob/d648375f13b4a4efd4cd35247098679fce5d4bcd/torch/optim/adamw.py#L321). This would significantly speed-up your optimizer while having literally no drawbacks. 

If you're interested i could take a look and implement this myself, but it would be in 1-2 weeks when i'm less busy

**Comment by XingyuXie** [comment]
Hi, @bonlime 

Thanks for your very valuable suggestions. We will try to implement this "torch._foreach" function.  
Of course, if you have time, you can also help. Many thanks!!

Best

**Comment by filonenkoa** [comment]
@bonlime, I'd also apreciate your contribution.
