### ISSUE TITLE
Typo in the paper

### ISSUE THREAD

**Issue by Tomarchelone** [sail-sg/Adan#15]
Looking at [arxiv](https://arxiv.org/pdf/2208.06677.pdf) version. In Appendix C in the last two lines of the Eq. 10 and the first line of the following update rule: `\theta` in the last term should have index `k-1` instead of `k`.

(Not sure if this is the appropriate place to report paper typos, please tell me if there is a more sutable one).

**Comment by XingyuXie** [comment]
@Tomarchelone you are right. Thanks for pointing out this. We will refine it in our next update.

It's ok to report paper typos here. Other problems are also welcome to inform us in any way. Thanks again.

Best
