### ISSUE TITLE
Adan相比于SGD在前 74 epochs保持领先，但是后续收敛变慢，我改如何调整lr等超参数？

### ISSUE THREAD

**Issue by liiicon** [sail-sg/Adan#39]
optimizer = Adan(pg0,lr = 1e-3, betas=(0.98, 0.92, 0.99), eps=1.0e-08, weight_decay=0.02)，
![image](https://github.com/sail-sg/Adan/assets/69030185/e5819bb7-7339-414e-b582-3667d2ca8ffe)
Black is SGD,pink is Adan.

**Comment by XingyuXie** [comment]
请问sgd的lr是多少？
其次，可以设置beta3为0.999，以及增大lr以及warmup steps进行尝试。

**Comment by liiicon** [comment]
sgd的lr是0.01。我会尝试您的建议，十分感谢您的帮助！
