### ISSUE TITLE
Beta values are not same

### ISSUE THREAD

**Issue by JaheimLee** [sail-sg/Adan#4]
According to your paper, you used adan with β1 = 0.02, β2 = 0.01, and β3 = 0.01 when fine-tuning Bert. But in your config file, they are all 0.9x like [here](https://github.com/sail-sg/Adan/blob/2dcf1254cf8c112dfc1c1a17f385e2ae4b3240b3/NLP/BERT/config/finetuning/sst_2-adan.yaml#L43). Which is right?

**Comment by XingyuXie** [comment]
Hi, @JaheimLee,

**The beta in the paper is actually the 1-beta in the code**. To maintain comparability with the results of some previous theoretical papers, such as (https://arxiv.org/abs/2112.03459), we need to set 

$$ \mathbf{m_k} = (1-{\color{orange}\beta_1})\mathbf{m_{k-1}} + {\color{orange}\beta_1} \mathbf{g_k}.$$

But in the code, to maintain the user's usage habits (we are used to setting the moment coefficient between 0.9-1), we have switched them, that is, 

$$ \mathbf{m_k} = {\color{orange}\beta_1}  \mathbf{m_{ k-1 }} + (1-{\color{orange}\beta_1})\mathbf{g_k}.$$

Thanks for the question, we have added some notifications on the homepage.
