### ISSUE TITLE
Is there a TensorFlow/Keras implementation?

### ISSUE THREAD

**Issue by cmsflash** [sail-sg/Adan#6]
Is there a TensorFlow/Keras implementation of Adan? If no official version, do you know of any third-party implementation? Or alternatively, how many lines would you expect an implementation to have? (If not much I may do it myself and ask for your review if you have time.)

**Comment by XingyuXie** [comment]
Hi, @cmsflash 
We will try to implement Keras 2.0+ version in the next few days, but we do not have more computing resources to test the training performance of this version. **It can only be used as a reference for you.**

About the lines: we have implemented it in Keras 1.0, it is about 100 lines.

**Comment by cmsflash** [comment]
Thank you so much! It would be greatly appreciated if you can ping this thread when the Keras 2.0 version is available.

Could you provide a link to the Keras 1.0 version?

**Comment by XingyuXie** [comment]
Hi, @cmsflash ,

The attachment is the implementation of Adan based on Keras 1.0. 
[adan-keras.py.zip](https://github.com/sail-sg/Adan/files/9504455/adan-keras.py.zip)

**Warning: This version has not been tested for model training. It can only be used as a reference.**

**Comment by henghamao** [comment]
Thanks for the great work!
We're interested in the work and would like to try the performance impact on our existed models.

Is there a tensorflow version?
I tried keras version you provided on the above.
After modified some import lines, like
```
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.optimizers import Optimizer
```
The errors are
'''
 NotImplementedError: `_resource_apply_dense` must be implemented in subclasses.
'''
Tensorflow version might need to implement some necessary interfaces.

**Comment by cmsflash** [comment]
@XingyuXie Thank you for the information! I will try to implement a TF2.0/TF Keras version and let you know if I finish.

**Comment by XingyuXie** [comment]
Hi @henghamao,

Thank you for your interest. At present, we will implement a version of Adan based on Keras 2.0+ as soon as possible, and then we will consider implementing it in TF 2.0+. 

We will update the progress on this issue.

Thanks again.

**Comment by DenisVorotyntsev** [comment]
I implemeted Adan in tf2.3+ - https://github.com/DenisVorotyntsev/Adan
