### ISSUE TITLE
The BERT finetuning get_data file error?

### ISSUE THREAD

**Issue by NoahDDavis** [sail-sg/Adan#9]
Thanks for the inspiring work! However the ``TASK2PATH`` paths in ``download_glue_data.py`` under directory ``./NLP/BERT/`` seems to have denied permission to access. e.g. "https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FCoLA.zip?alt=media&token=46d5e637-3411-4188-bc44-5809b5bfb5f4"

**Comment by XingyuXie** [comment]
Hi @NoahDDavis,

First of all, please ensure that you have access right to your data dir on your machine. And also, refer to the repo of GLUE (https://github.com/nyu-mll/GLUE-baselines)  for more detailed steps of data downloading. 

Sometimes,  we may be blocked from `s3.amazonaws.com`. In this case, more steps are needed (see the official repo).

Best

**Comment by NoahDDavis** [comment]
Thanks very much for your reply and I have solved the previous problem! However, I come across a new bug when trying to fine-tune BERT, as there is no ``acc_test.py ``under path/to/fairseq/examples/roberta/config/finetuning/ (see https://github.com/facebookresearch/fairseq/tree/main/examples/roberta/config/finetuning), is this py file generated in some preprocesing step?

I would appreciate it very much if you could reply.

Thanks

**Comment by XingyuXie** [comment]
The file is here (https://github.com/sail-sg/Adan/blob/main/NLP/BERT/config/finetuning/acc_test.py).
It is implemented by us according to the discussion in the Fairseq repo. 
There is no official inference script `.py` for testing all tasks; the example is only for the task of `RTE`.

Best

**Comment by NoahDDavis** [comment]
Got it. Thanks very much!
